# Test against this version of Node.js
environment:
  nodejs_version: "5"
  jspm_github_auth_token:
    secure: 4sWCirmMm0kNzOax0nyuH/kuN9vdFFEAVcDjiL3xNDxGcgAF9vTg7WEoufuC1gde

# Install scripts. (runs after repo cloning)
install:
  # Get the latest stable version of Node.js or io.js
  - ps: Install-Product node $env:nodejs_version
  - npm install -g gulp jspm
  - jspm config registries.github.auth xx
  # install modules
  - npm install
  - jspm install
  
# Post-install test scripts.
test_script:
  # Output useful info for debugging.
  - node --version
  - npm --version
  # run tests
  - gulp lint
  - gulp test

# Don't actually build.
build: off

notifications:
  - provider: Slack
    incoming_webhook:
      secure: vEkNTGdxrec+HtMuHg87gPDSbcATux8FurC+ntE6+y9HzsbAkhizj5UIEA9ccKj0RC2SBkJECVo3dX9K5OQunXHRNFxBbvZrS08gMGRIx2I=

cache:
 - node_modules
 - '%APPDATA%\npm-cache'